# Generated by Django 5.1.2 on 2024-11-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_rename_theme_question_theme_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='title',
        ),
    ]
