# Generated by Django 5.1.2 on 2024-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_rename_name_package_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
