# Generated by Django 5.1.2 on 2024-11-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_alter_round_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
